# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  blogapi:
    image: blogapi
    build:
      context: .
      dockerfile: BlogAPI/Dockerfile
    ports:
      - 8080:80
