// <auto-generated />
using BlogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220716162355_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BlogAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bradley",
                            LastName = "Cooper"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sonoya",
                            LastName = "Mizuno"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            LastName = "Wick"
                        },
                        new
                        {
                            Id = 4,
                            Address = "154 Road, NYC 90454",
                            FirstName = "Mary Elise",
                            LastName = "Windstead"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Scarlett",
                            LastName = "Amancia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
