// <auto-generated />
using BlogServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BlogServer.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestModelOtherProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestModels");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            TestModelName = "First name",
                            TestModelOtherProperty = "Some other property name"
                        },
                        new
                        {
                            Id = 20,
                            TestModelName = "Sec name",
                            TestModelOtherProperty = "Some sec property name"
                        },
                        new
                        {
                            Id = 30,
                            TestModelName = "Tres name",
                            TestModelOtherProperty = "Some tres property name"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
